# License           : GPL3
# Author            : Jingxin Fu <jingxinfu.tj@gmail.com>
# Date              : 11/02/2020
# Last Modified Date: 20/02/2020
# Last Modified By  : Jingxin Fu <jingxinfu.tj@gmail.com>
language: python
os: 
  - linux
python:
  - "3.5" 
  - "3.6"      
  - "3.7"
  - "3.8"

    #addons:
    #  apt:
    #    upadate: true
    #    packages:
    #      - libxml2-dev
    #      - libopenblas-base 
    #      - r-base

# command to install dependencies
install:
  - pip3 install .
  - wget https://cran.r-project.org/src/base/R-3/R-3.5.0.tar.gz
  - tar -xzf R-3.5.0.tar.gz
  - cd R-3.5.0
  - ./configure && make && make install
  - cd ../

# command to run tests
script: 
  - mkdir ~/R/
  - echo "R_LIBS=~/R" > ~/.Renviron 
  - R --version
  - pytest
